name: Build and push image

on:
  push:
    branches:
      - 'develop'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@master

      - run: echo "VERSION=$(cat VERSION)" >> $GITHUB_ENV         

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: false
          tags: kemicoin/kemicoin-backend:${{ env.VERSION }}

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

      - name: Push to GitHub Packages
        uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: hecklawert/kemicoin-api/kemicoin-backend
          tags: ${{ env.VERSION  }},latest 

